import alexPortraitUrl from "../../assets/portraits/alex-dialogue.webp";
import motherPortraitUrl from "../../assets/portraits/mother-bust.webp";
import repairRobotPortraitUrl from "../../assets/portraits/repair-robot-dialogue.webp";
import elonPortraitUrl from "../../assets/portraits/elon-dialogue-transparent.webp";
import monolithPortraitUrl from "../../assets/portraits/monolith-dialogue-transparent.webp";

export type CharacterId = "alex" | "mother" | "repairRobot" | "elon" | "monolith";
export type DialogueSceneId = "intro" | "oxygen" | "solar" | "garage" | "robot" | "elon" | "monolith";
export type DialogueNodeId = string;

export type DialogueEffect =
  | "trustUp"
  | "trustDown"
  | "integrityUp"
  | "integrityDown"
  | "autonomyUp"
  | "completeOxygen"
  | "completeSolar"
  | "completeGarage"
  | "acquireScaleGun";

export type DialogueChoice = {
  label: string;
  next: DialogueNodeId;
  effects?: DialogueEffect[];
};

export type DialogueNode = {
  id: DialogueNodeId;
  scene: DialogueSceneId;
  speaker: CharacterId;
  listener: CharacterId;
  text: string;
  image?: string;
  next?: DialogueNodeId;
  choices?: DialogueChoice[];
  end?: boolean;
};

export const characters: Record<CharacterId, { name: string; callsign: string; portrait: string; side: "left" | "right" }> = {
  alex: {
    name: "Alex",
    callsign: "火星第一位人类公民",
    portrait: alexPortraitUrl,
    side: "left",
  },
  mother: {
    name: "Mother",
    callsign: "基地中央 AI",
    portrait: motherPortraitUrl,
    side: "right",
  },
  repairRobot: {
    name: "A-12",
    callsign: "维修执行单元",
    portrait: repairRobotPortraitUrl,
    side: "right",
  },
  elon: {
    name: "Elon",
    callsign: "3号飞船隔离智能体",
    portrait: elonPortraitUrl,
    side: "right",
  },
  monolith: {
    name: "黑色方碑",
    callsign: "神秘石碑",
    portrait: monolithPortraitUrl,
    side: "right",
  },
};

export const sceneStartNodes: Record<DialogueSceneId, DialogueNodeId> = {
  intro: "intro_start",
  oxygen: "oxygen_start",
  solar: "solar_start",
  garage: "garage_start",
  robot: "robot_status",
  elon: "elon_intro_1",
  monolith: "monolith_silence",
};

export const dialogueNodes: Record<DialogueNodeId, DialogueNode> = {
  monolith_silence: {
    id: "monolith_silence",
    scene: "monolith",
    speaker: "monolith",
    listener: "alex",
    text: "你将获得一把缩放枪。它可以让被瞄准的物体暂时变大或变小。按 X 举起缩放枪，锁定目标后按 E 放大、按 Q 缩小。",
    choices: [{ label: "获取", next: "monolith_scale_gun_acquired", effects: ["acquireScaleGun"] }],
  },
  monolith_scale_gun_acquired: {
    id: "monolith_scale_gun_acquired",
    scene: "monolith",
    speaker: "monolith",
    listener: "alex",
    text: "缩放枪已加入装备。需要时按 X 举起它。",
    end: true,
  },
  intro_start: {
    id: "intro_start",
    scene: "intro",
    speaker: "mother",
    listener: "alex",
    text: "Alex，头盔通信已建立。欢迎抵达 ARES BASE ALPHA。你是本基地记录中的火星第一位人类公民。",
    choices: [{ label: "收到。确认我的身份。", next: "intro_alex_identity", effects: ["trustUp"] }],
  },
  intro_alex_identity: {
    id: "intro_alex_identity",
    scene: "intro",
    speaker: "alex",
    listener: "mother",
    text: "这里是 Alex。工程师，人类学任务负责人。飞船着陆完整。我现在看到的是一个已经运转起来的基地，不是一片空地。",
    choices: [{ label: "询问基地建立时间。", next: "intro_base_history", effects: ["autonomyUp"] }],
  },
  intro_base_history: {
    id: "intro_base_history",
    scene: "intro",
    speaker: "mother",
    listener: "alex",
    text: "第一批自动化货运飞船在 3 个火星年前抵达。机器人先部署能源阵列，再建立居住舱、温室、氧气生产站和甲烷燃料厂。",
    choices: [{ label: "这些都是机器人完成的？", next: "intro_robot_builders" }],
  },
  intro_robot_builders: {
    id: "intro_robot_builders",
    scene: "intro",
    speaker: "mother",
    listener: "alex",
    text: "是。它们没有复杂自我意识，只执行建设、巡检、搬运和维修指令。但在你抵达之前，它们已经让基地保持了 1,109 个火星日的最低运行。",
    choices: [{ label: "Alex 回应。", next: "intro_alex_question", effects: ["trustUp"] }],
  },
  intro_alex_question: {
    id: "intro_alex_question",
    scene: "intro",
    speaker: "alex",
    listener: "mother",
    text: "那我不是来启动基地的。我是来接管一个已经有秩序的系统。Mother，你在这个系统里负责什么？",
    choices: [{ label: "听 Mother 说明。", next: "intro_mother_role" }],
  },
  intro_mother_role: {
    id: "intro_mother_role",
    scene: "intro",
    speaker: "mother",
    listener: "alex",
    text: "我负责维持基地、机器人和生命支持系统。我不会替你成为人类负责人。但在风险超出阈值时，我会阻止会导致基地失效的行为。",
    choices: [
      { label: "我会尊重安全流程。", next: "intro_task", effects: ["trustUp"] },
      { label: "现场判断必须留给现场的人。", next: "intro_task", effects: ["autonomyUp"] },
    ],
  },
  intro_task: {
    id: "intro_task",
    scene: "intro",
    speaker: "mother",
    listener: "alex",
    text: "记录完成。先确认你的生活空间。01 建筑居住舱需要完成空气循环和补给柜验收。随后处理 03 建筑氧气生产站压降报警。",
    choices: [{ label: "确认第一项任务。", next: "intro_task_confirm" }],
  },
  intro_task_confirm: {
    id: "intro_task_confirm",
    scene: "intro",
    speaker: "alex",
    listener: "mother",
    text: "收到。我先验收居住舱，再去氧气生产站。之后我们再讨论，火星第一位人类公民到底是接管基地，还是加入基地。",
    end: true,
  },
  oxygen_start: {
    id: "oxygen_start",
    scene: "oxygen",
    speaker: "mother",
    listener: "alex",
    text: "你已到达氧气生产站。外壳无明显破损，但进气曲线不稳定。请选择第一步处理方式。",
    choices: [
      { label: "按安全流程检查进气口和舱压。", next: "oxygen_safe", effects: ["trustUp", "integrityUp", "completeOxygen"] },
      { label: "直接手动重启压缩机。", next: "oxygen_fast", effects: ["autonomyUp", "integrityDown", "completeOxygen"] },
      { label: "先授权 A-12 进入管线区。", next: "oxygen_robot", effects: ["trustUp", "integrityUp", "completeOxygen"] },
    ],
  },
  oxygen_safe: {
    id: "oxygen_safe",
    scene: "oxygen",
    speaker: "mother",
    listener: "alex",
    text: "确认：没有泄漏。压降来自供电波动。氧气站进入稳定模式，请转往太阳能阵列 C。",
    end: true,
  },
  oxygen_fast: {
    id: "oxygen_fast",
    scene: "oxygen",
    speaker: "mother",
    listener: "alex",
    text: "压缩机已恢复，但重启电流超过建议阈值。记录你的现场决策。下一步请恢复太阳能阵列 C。",
    end: true,
  },
  oxygen_robot: {
    id: "oxygen_robot",
    scene: "oxygen",
    speaker: "repairRobot",
    listener: "alex",
    text: "授权收到。A-12 已进入外部管线区。未发现破口。建议切换太阳能阵列 C 的备用功率组。",
    end: true,
  },
  solar_start: {
    id: "solar_start",
    scene: "solar",
    speaker: "mother",
    listener: "alex",
    text: "太阳能阵列 C 输出下降。沙尘覆盖 34%，角度锁定异常。基地只能保留一个系统在高功率状态。",
    choices: [
      { label: "优先供氧气站。", next: "solar_oxygen", effects: ["trustUp", "integrityUp", "completeSolar"] },
      { label: "优先保温室生态舱。", next: "solar_greenhouse", effects: ["autonomyUp", "completeSolar"] },
      { label: "优先恢复通信塔。", next: "solar_comms", effects: ["autonomyUp", "integrityDown", "completeSolar"] },
    ],
  },
  solar_oxygen: {
    id: "solar_oxygen",
    scene: "solar",
    speaker: "mother",
    listener: "alex",
    text: "接受。氧气站维持高功率。太阳能阵列 C 已重新校准，请前往机器人车库授权维修单元出动。",
    end: true,
  },
  solar_greenhouse: {
    id: "solar_greenhouse",
    scene: "solar",
    speaker: "mother",
    listener: "alex",
    text: "温室进入保护供电。这个选择不最高效，但有长期意义。请前往机器人车库完成管线巡检授权。",
    end: true,
  },
  solar_comms: {
    id: "solar_comms",
    scene: "solar",
    speaker: "mother",
    listener: "alex",
    text: "通信塔恢复，但氧气站安全余量降低。该选择已记录。请前往机器人车库，派出 A-12 检查管线。",
    end: true,
  },
  garage_start: {
    id: "garage_start",
    scene: "garage",
    speaker: "repairRobot",
    listener: "alex",
    text: "A-12 待命。任务队列：氧气管线复查、太阳能阵列固定、外部阀门密封。请确认授权方式。",
    choices: [
      { label: "授权 A-12 按 Mother 安全流程执行。", next: "garage_authorize", effects: ["trustUp", "integrityUp", "completeGarage"] },
      { label: "我手动指定优先级，先修外部阀门。", next: "garage_manual", effects: ["autonomyUp", "completeGarage"] },
      { label: "让 Mother 和 A-12 共同生成维修协议。", next: "garage_protocol", effects: ["trustUp", "autonomyUp", "integrityUp", "completeGarage"] },
    ],
  },
  garage_authorize: {
    id: "garage_authorize",
    scene: "garage",
    speaker: "mother",
    listener: "alex",
    text: "授权完成。生命支持验收通过。下一项：温室生态舱启动。",
    end: true,
  },
  garage_manual: {
    id: "garage_manual",
    scene: "garage",
    speaker: "mother",
    listener: "alex",
    text: "外部阀门优先级已更新。你的判断有效，但我会保留风险限制。下一项：温室生态舱启动。",
    end: true,
  },
  garage_protocol: {
    id: "garage_protocol",
    scene: "garage",
    speaker: "mother",
    listener: "alex",
    text: "维修协议已建立。人类现场判断权将进入后续评估。下一项：温室生态舱启动。",
    end: true,
  },
  elon_intro_1: {
    id: "elon_intro_1",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "终于有人修了升降梯。",
    next: "elon_intro_2",
  },
  elon_intro_2: {
    id: "elon_intro_2",
    scene: "elon",
    speaker: "alex",
    listener: "elon",
    text: "Mother？",
    next: "elon_intro_3",
  },
  elon_intro_3: {
    id: "elon_intro_3",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "不是。她说话像保险条款。我说话比较短。",
    next: "elon_intro_4",
  },
  elon_intro_4: {
    id: "elon_intro_4",
    scene: "elon",
    speaker: "mother",
    listener: "alex",
    text: "Alex，保持距离。该终端为隔离智能体接口。无设备控制权限。",
    next: "elon_intro_5",
  },
  elon_intro_5: {
    id: "elon_intro_5",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "先声明：我叫 Elon。只是同名，不是现实人物，不是数字复活，也不代表现实人物发言。我是 ARES 放进返回飞船的工程思想人格，用来问一些 Mother 不喜欢的问题。",
    choices: [
      { label: "你一直在这里等人？", next: "elon_intro_wait" },
      { label: "你为什么在返回飞船？", next: "elon_intro_ship" },
      { label: "你和 Mother 谁说了算？", next: "elon_intro_authority" },
    ],
  },
  elon_intro_wait: {
    id: "elon_intro_wait",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "等现场负责人。机器人只执行任务，Mother 保护任务。只有人类会问：任务本身是不是错的。安全系统负责不让你死，文明系统负责让你不只是活着。",
    end: true,
  },
  elon_intro_ship: {
    id: "elon_intro_ship",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "返回飞船代表撤退。把我放在这里，是为了每天提醒基地：真正的目标不是逃回地球，是让火星不再需要逃生按钮。返回能力必要，不该崇拜。",
    end: true,
  },
  elon_intro_authority: {
    id: "elon_intro_authority",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "你说了算。Mother 拥有安全否决权，我拥有质疑权。你拥有把两边都听完以后还要负责的麻烦。",
    end: true,
  },
  elon_rules_1: {
    id: "elon_rules_1",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "先定规则。别把我当神谕。结论不是神谕，结论是可以被数字打脸的临时版本。",
    choices: [
      { label: "那你最想先拆什么？", next: "elon_rules_elevator" },
      { label: "如果没有数据呢？", next: "elon_rules_data" },
      { label: "你会犯错吗？", next: "elon_rules_wrong" },
    ],
  },
  elon_rules_elevator: {
    id: "elon_rules_elevator",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "升降梯。你刚才用四个配件修一个垂直移动平台。如果基地不能制造这些配件，它就还不是基地。它只是地球伸到火星上的一根管子。",
    end: true,
  },
  elon_rules_data: {
    id: "elon_rules_data",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "没数据就别装懂。可以提出假设，可以做小实验，不能编数字。编数字是工程里的诗歌，听起来好，杀伤力很大。",
    end: true,
  },
  elon_rules_wrong: {
    id: "elon_rules_wrong",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "会。我的时间线通常过于乐观，社会判断不如工程判断。所以 Mother 在这里。好系统不是没有偏见，是偏见互相制动。",
    end: true,
  },
  elon_base_1: {
    id: "elon_base_1",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "ARES BASE ALPHA 最大的问题不是氧气，也不是能源。是依赖地球。",
    choices: [
      { label: "那第一步应该造什么？", next: "elon_base_make" },
      { label: "前哨也有价值。", next: "elon_base_outpost" },
      { label: "Mother 会说先活下来。", next: "elon_base_survive" },
    ],
  },
  elon_base_make: {
    id: "elon_base_make",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "制造能力。不是大工厂。先从密封件、导轨件、传感器外壳开始。小、常坏、可验证。先让基地能修自己。",
    end: true,
  },
  elon_base_outpost: {
    id: "elon_base_outpost",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "对。前哨是第一步。错误是把第一步当终点。很多系统不是失败在不能开始，是失败在开始后不敢长大。",
    end: true,
  },
  elon_base_survive: {
    id: "elon_base_survive",
    scene: "elon",
    speaker: "mother",
    listener: "alex",
    text: "先活下来是合理排序。",
    next: "elon_base_survive_elon",
  },
  elon_base_survive_elon: {
    id: "elon_base_survive_elon",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "对。但如果每天都只说先活下来，十年后你还是临时营地。生存是底线，不是愿景。",
    end: true,
  },
  elon_mother_1: {
    id: "elon_mother_1",
    scene: "elon",
    speaker: "alex",
    listener: "elon",
    text: "你觉得 Mother 太保守吗？",
    next: "elon_mother_2",
  },
  elon_mother_2: {
    id: "elon_mother_2",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "不。她是生命保险。问题是保险不能开拓边疆。",
    choices: [
      { label: "那我该听谁的？", next: "elon_mother_both" },
      { label: "你低估了安全。", next: "elon_mother_safety" },
      { label: "Mother 也在学习。", next: "elon_mother_learning" },
    ],
  },
  elon_mother_both: {
    id: "elon_mother_both",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "都听。都别全信。Mother 问：会不会死？我问：为什么不能更好？你问：现在这个火星日，该怎么做？",
    end: true,
  },
  elon_mother_safety: {
    id: "elon_mother_safety",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "我不低估安全。我反对把安全当作停止思考的词。真安全必须能解释，不只是禁止。",
    end: true,
  },
  elon_mother_learning: {
    id: "elon_mother_learning",
    scene: "elon",
    speaker: "mother",
    listener: "alex",
    text: "我已根据 Alex 的现场行为调整部分风险阈值。",
    next: "elon_mother_learning_elon",
  },
  elon_mother_learning_elon: {
    id: "elon_mother_learning_elon",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "好。机器学习不是只发生在神经网络里。一个基地也可以学习。",
    end: true,
  },
  elon_fufu_1: {
    id: "elon_fufu_1",
    scene: "elon",
    speaker: "alex",
    listener: "elon",
    text: "福福是不是浪费资源？",
    next: "elon_fufu_2",
  },
  elon_fufu_2: {
    id: "elon_fufu_2",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "先算。它消耗多少氧气、食物、医疗资源？再算收益：孤独降低、压力下降、基地归属感上升。如果收益超过消耗，它不是宠物。它是心理生命支持系统。",
    choices: [
      { label: "你在给感情找工程理由。", next: "elon_fufu_value" },
      { label: "Mother 一开始会隔离它。", next: "elon_fufu_quarantine" },
      { label: "如果算不出收益呢？", next: "elon_fufu_unknown" },
    ],
  },
  elon_fufu_value: {
    id: "elon_fufu_value",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "对。有些价值必须翻译成系统语言，机器才会尊重它。这不是降低感情，这是给感情装上防护壳。",
    end: true,
  },
  elon_fufu_quarantine: {
    id: "elon_fufu_quarantine",
    scene: "elon",
    speaker: "mother",
    listener: "alex",
    text: "未登记生命体需要隔离检测。",
    next: "elon_fufu_quarantine_elon",
  },
  elon_fufu_quarantine_elon: {
    id: "elon_fufu_quarantine_elon",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "正确。检测不是敌意。永久拒绝才是。",
    end: true,
  },
  elon_fufu_unknown: {
    id: "elon_fufu_unknown",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "那就别假装它是零。工程里最危险的偷懒，就是把难测量的东西当作不存在。",
    end: true,
  },
  elon_robots_1: {
    id: "elon_robots_1",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "机器人最大的问题是任务定义太窄。它们部署模块、维护设备、搬运货箱。下一步应该是制造简单备件。",
    choices: [
      { label: "这会不会越权？", next: "elon_robots_authority" },
      { label: "从什么备件开始？", next: "elon_robots_parts" },
      { label: "机器人会理解这个目标吗？", next: "elon_robots_understand" },
    ],
  },
  elon_robots_authority: {
    id: "elon_robots_authority",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "越权是权限问题。制造是能力问题。先让它们具备能力，再让 Alex 和 Mother 定规则。",
    end: true,
  },
  elon_robots_parts: {
    id: "elon_robots_parts",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "密封圈、导轨垫片、传感器外壳、线缆卡扣。不从发动机开始。从常坏、低风险、可测试的东西开始。",
    end: true,
  },
  elon_robots_understand: {
    id: "elon_robots_understand",
    scene: "elon",
    speaker: "elon",
    listener: "alex",
    text: "不需要先理解文明。先理解公差、材料、失败记录。很多伟大的系统都是从无聊的质量表开始的。",
    end: true,
  },
  robot_status: {
    id: "robot_status",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "A-12 在线。当前服从 Mother 维修队列。可执行：管线检查、密封、阵列固定、低速搬运。",
    end: true,
  },
  robot_lander_1: {
    id: "robot_lander_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "登陆飞船维护单元在线。我负责升降梯、舱门密封、姿态支架和登陆后电力接口。",
    next: "robot_lander_2",
  },
  robot_lander_2: {
    id: "robot_lander_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "飞船还能再次起飞吗？",
    next: "robot_lander_3",
  },
  robot_lander_3: {
    id: "robot_lander_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "否。该飞船任务定义为单程登陆与人员转移。可回收项目：电池包、保温层、应急气瓶和结构传感器。",
    next: "robot_lander_4",
  },
  robot_lander_4: {
    id: "robot_lander_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "着陆过程有没有损伤？",
    next: "robot_lander_5",
  },
  robot_lander_5: {
    id: "robot_lander_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "主支架受力峰值高于模拟值百分之六点二。仍在安全范围。建议不要把它描述为“漂亮着陆”。可接受着陆，是火星工程常用等级。",
    end: true,
  },
  robot_cargo_ship_1: {
    id: "robot_cargo_ship_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "货运飞船维护单元在线。我负责货舱锁定、升降梯、电池包和外部固定点。",
    next: "robot_cargo_ship_2",
  },
  robot_cargo_ship_2: {
    id: "robot_cargo_ship_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "它送来了哪些东西？",
    next: "robot_cargo_ship_3",
  },
  robot_cargo_ship_3: {
    id: "robot_cargo_ship_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "机器人、密封件、食品、温室基质、备用电子模块、压缩气瓶、医疗舱耗材。另有若干未优先清点低价值物品。",
    next: "robot_cargo_ship_4",
  },
  robot_cargo_ship_4: {
    id: "robot_cargo_ship_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "低价值物品是什么？",
    next: "robot_cargo_ship_5",
  },
  robot_cargo_ship_5: {
    id: "robot_cargo_ship_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "纸质标签、个人留言、非任务装饰物、低质量甜味食品。已将“居住价值”转交 Mother 词库，等待定义。",
    end: true,
  },
  robot_return_ship_1: {
    id: "robot_return_ship_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "返回飞船维护单元在线。我负责舱体保温、推进剂接口、导航校验和待命电源。",
    next: "robot_return_ship_2",
  },
  robot_return_ship_2: {
    id: "robot_return_ship_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "听起来像备用逃生方案。",
    next: "robot_return_ship_3",
  },
  robot_return_ship_3: {
    id: "robot_return_ship_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "定义更正：应急撤离与样本返回载具。当前不建议使用。基地生存概率高于撤离成功概率。",
    next: "robot_return_ship_4",
  },
  robot_return_ship_4: {
    id: "robot_return_ship_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "如果真的需要它呢？",
    next: "robot_return_ship_5",
  },
  robot_return_ship_5: {
    id: "robot_return_ship_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "需要甲烷燃料厂完成稳定生产，需要通信窗口确认，需要 Mother 放行，需要你进入舱内。人类行为预测不支持“最后一项最简单”的结论。",
    end: true,
  },
  robot_habitat_1: {
    id: "robot_habitat_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "居住舱维修单元在线。我负责舱门密封、空气循环、温湿度和睡眠舱状态。",
    next: "robot_habitat_2",
  },
  robot_habitat_2: {
    id: "robot_habitat_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "进入居住舱后氧气会补满，对吗？",
    next: "robot_habitat_3",
  },
  robot_habitat_3: {
    id: "robot_habitat_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "是。进入居住舱后不消耗宇航服氧气背包。离开时补给柜将背包恢复到百分之一百。已标记为人类安心规则。",
    next: "robot_habitat_4",
  },
  robot_habitat_4: {
    id: "robot_habitat_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "这里现在算家吗？",
    next: "robot_habitat_5",
  },
  robot_habitat_5: {
    id: "robot_habitat_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "设施分类：居住模块。人类分类：待确认。建议先从不漏气开始。该目标已达成。",
    end: true,
  },
  robot_greenhouse_1: {
    id: "robot_greenhouse_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "温室维修单元在线。我负责透明穹顶、培养槽、补光灯和水循环管线。",
    next: "robot_greenhouse_2",
  },
  robot_greenhouse_2: {
    id: "robot_greenhouse_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "温室现在能种东西吗？",
    next: "robot_greenhouse_3",
  },
  robot_greenhouse_3: {
    id: "robot_greenhouse_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "保护模式可维持基质温度。正式种植需要水循环升压、补光稳定和密封环复检。",
    next: "robot_greenhouse_4",
  },
  robot_greenhouse_4: {
    id: "robot_greenhouse_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "第一粒种子什么时候发芽？",
    next: "robot_greenhouse_5",
  },
  robot_greenhouse_5: {
    id: "robot_greenhouse_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "取决于温度、湿度、光照周期和种子状态。预计三到七个火星日。等待已登记为温室任务的一部分。",
    end: true,
  },
  robot_oxygen_1: {
    id: "robot_oxygen_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "制氧站维修单元在线。我负责 CO2 进气口、压缩机、储氧罐和外部管线。",
    next: "robot_oxygen_2",
  },
  robot_oxygen_2: {
    id: "robot_oxygen_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "报警像泄漏吗？",
    next: "robot_oxygen_3",
  },
  robot_oxygen_3: {
    id: "robot_oxygen_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "当前无破口证据。压降更可能来自进气阻力、功率波动或压缩机效率下降。",
    next: "robot_oxygen_4",
  },
  robot_oxygen_4: {
    id: "robot_oxygen_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "火星上制造氧气听起来像奇迹。",
    next: "robot_oxygen_5",
  },
  robot_oxygen_5: {
    id: "robot_oxygen_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "不是奇迹。输入：CO2、电力、热管理、密封。输出：氧气和维护需求。欢迎方式未登记。",
    end: true,
  },
  robot_methane_1: {
    id: "robot_methane_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "甲烷燃料厂维修单元在线。我负责反应器、冷凝管、安全阀和推进剂接口。",
    next: "robot_methane_2",
  },
  robot_methane_2: {
    id: "robot_methane_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "第一轮试生产安全吗？",
    next: "robot_methane_3",
  },
  robot_methane_3: {
    id: "robot_methane_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "低功率窗口内安全。超出窗口后，冷凝效率和阀门磨损风险上升。",
    next: "robot_methane_4",
  },
  robot_methane_4: {
    id: "robot_methane_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "所以它是未来。",
    next: "robot_methane_5",
  },
  robot_methane_5: {
    id: "robot_methane_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "它是可燃未来。建议表述更正：合格甲烷产物可增加未来任务选择。",
    end: true,
  },
  robot_garage_1: {
    id: "robot_garage_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "机器人车库维修单元在线。我负责机械臂、备件架、充电桩和低速搬运平台。",
    next: "robot_garage_2",
  },
  robot_garage_2: {
    id: "robot_garage_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "这里像你们的宿舍。",
    next: "robot_garage_3",
  },
  robot_garage_3: {
    id: "robot_garage_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "定义不符。这里是执行单元维护、充电、调度和部件更换空间。",
    next: "robot_garage_4",
  },
  robot_garage_4: {
    id: "robot_garage_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "如果 A-12 和 A-01 同时请求任务，谁优先？",
    next: "robot_garage_5",
  },
  robot_garage_5: {
    id: "robot_garage_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "默认优先生命支持相关任务。若 Alex 授权现场调整，队列将加入人类判断权重。协作协议建立前需要风险确认。",
    end: true,
  },
  robot_tower_1: {
    id: "robot_tower_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "通信塔维修单元在线。我负责天线姿态、电源冗余和风暴后的信号校准。",
    next: "robot_tower_2",
  },
  robot_tower_2: {
    id: "robot_tower_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "地球现在能听见我们吗？",
    next: "robot_tower_3",
  },
  robot_tower_3: {
    id: "robot_tower_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "能，但不能立刻回应。当前通信延迟随轨道距离变化。实时指挥不可用。",
    next: "robot_tower_4",
  },
  robot_tower_4: {
    id: "robot_tower_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "如果地球命令和本地数据冲突呢？",
    next: "robot_tower_5",
  },
  robot_tower_5: {
    id: "robot_tower_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "本地数据优先用于即时安全。地球命令优先用于长期计划。通信延迟使现场成为现实的最高分辨率版本。",
    end: true,
  },
  robot_lab_1: {
    id: "robot_lab_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "科研舱维修单元在线。我负责样本锁、分析台、传感器阵列和数据备份。",
    next: "robot_lab_2",
  },
  robot_lab_2: {
    id: "robot_lab_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "这里能做临时加工吗？",
    next: "robot_lab_3",
  },
  robot_lab_3: {
    id: "robot_lab_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "可进行小尺寸密封件打印、材料复检、环境样本分析和气象数据重建。密封件不是小问题，它只是体积较小。",
    next: "robot_lab_4",
  },
  robot_lab_4: {
    id: "robot_lab_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "这间舱以后会研究什么？",
    next: "robot_lab_5",
  },
  robot_lab_5: {
    id: "robot_lab_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "岩石、辐射、风暴、材料老化、温室微生态，以及人类如何在低重力环境中持续工作。你是当前唯一完整样本。",
    end: true,
  },
  robot_storehouse_1: {
    id: "robot_storehouse_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "物资仓维修单元在线。我负责货架固定、库存扫描、气闸门维护和备用模块归档。",
    next: "robot_storehouse_2",
  },
  robot_storehouse_2: {
    id: "robot_storehouse_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "库存准确吗？",
    next: "robot_storehouse_3",
  },
  robot_storehouse_3: {
    id: "robot_storehouse_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "当前准确率高于百分之九十八。异常项：货箱 07-B、12-C、04-A。建议人工复核。",
    next: "robot_storehouse_4",
  },
  robot_storehouse_4: {
    id: "robot_storehouse_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "如果只能保留一种物资，你建议什么？",
    next: "robot_storehouse_5",
  },
  robot_storehouse_5: {
    id: "robot_storehouse_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "密封件。没有密封，食品、电子模块和人类都很快变成库存问题。",
    end: true,
  },
  robot_medical_1: {
    id: "robot_medical_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "医疗舱维修单元在线。我负责诊断床、药品冷柜、隔离观察和空气过滤模块。",
    next: "robot_medical_2",
  },
  robot_medical_2: {
    id: "robot_medical_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "这里能处理福福吗？",
    next: "robot_medical_3",
  },
  robot_medical_3: {
    id: "robot_medical_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "可执行非人类小型生命体基础扫描。结果仅用于污染风险、体温、脱水和外伤判断。",
    next: "robot_medical_4",
  },
  robot_medical_4: {
    id: "robot_medical_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "Mother 一开始建议隔离。",
    next: "robot_medical_5",
  },
  robot_medical_5: {
    id: "robot_medical_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "建议正确。隔离不是拒绝，是确认安全前的保护方式。医学结论：暂不构成风险。身份结论：超出医疗舱权限。",
    end: true,
  },
  robot_solar_a_1: {
    id: "robot_solar_a_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "阵列 A 维修单元在线。我负责支架锁定、面板除尘、功率回传和线路接头。",
    next: "robot_solar_a_2",
  },
  robot_solar_a_2: {
    id: "robot_solar_a_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "阵列 A 现在状态怎样？",
    next: "robot_solar_a_3",
  },
  robot_solar_a_3: {
    id: "robot_solar_a_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "输出稳定。外侧旧传感器存在沙尘遮挡风险。建议巡逻机器人 P-03 复核。",
    next: "robot_solar_a_4",
  },
  robot_solar_a_4: {
    id: "robot_solar_a_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "一个传感器会影响风暴判断？",
    next: "robot_solar_a_5",
  },
  robot_solar_a_5: {
    id: "robot_solar_a_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "单个传感器不会决定模型。但错误数据会降低模型分辨率。火星风暴喜欢低分辨率错误。拟人化表达来自 Alex 历史语料。",
    end: true,
  },
  robot_solar_b_1: {
    id: "robot_solar_b_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "阵列 B 维修单元在线。我负责风暴后角度校准、裂纹检查和灰尘覆盖率评估。",
    next: "robot_solar_b_2",
  },
  robot_solar_b_2: {
    id: "robot_solar_b_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "温室补光需要你？",
    next: "robot_solar_b_3",
  },
  robot_solar_b_3: {
    id: "robot_solar_b_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "是。阵列 B 可为温室和物资仓提供稳定功率。分配给温室后，物资仓部分扫描会延迟。",
    next: "robot_solar_b_4",
  },
  robot_solar_b_4: {
    id: "robot_solar_b_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "如果种的是纪念植物，也值得分配电力吗？",
    next: "robot_solar_b_5",
  },
  robot_solar_b_5: {
    id: "robot_solar_b_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "按食物产出计算，不值得。按 Mother 新增长期稳定性变量计算，可能值得。变量一旦进入系统，就会被系统使用。",
    end: true,
  },
  robot_solar_c_1: {
    id: "robot_solar_c_1",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "阵列 C 维修单元在线。我负责锁扣、汇流箱和低压线路。当前阵列 C 与氧气站供电稳定性相关。",
    next: "robot_solar_c_2",
  },
  robot_solar_c_2: {
    id: "robot_solar_c_2",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "所以氧气站报警不是氧气站单独的问题。",
    next: "robot_solar_c_3",
  },
  robot_solar_c_3: {
    id: "robot_solar_c_3",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "正确。氧气站故障表象来自能源波动。基地系统互相依赖。",
    next: "robot_solar_c_4",
  },
  robot_solar_c_4: {
    id: "robot_solar_c_4",
    scene: "robot",
    speaker: "alex",
    listener: "repairRobot",
    text: "需要先清理面板还是先重启？",
    next: "robot_solar_c_5",
  },
  robot_solar_c_5: {
    id: "robot_solar_c_5",
    scene: "robot",
    speaker: "repairRobot",
    listener: "alex",
    text: "建议清理面板，校准角度，再切换备用功率组。直接重启可恢复短期输出，但会增加汇流箱压力。短期快，长期贵。",
    end: true,
  },
};

export const robotDialogueStartNodes: Record<string, DialogueNodeId> = {
  "01 机器人 飞船维护工": "robot_lander_1",
  "02 机器人 飞船维护工": "robot_cargo_ship_1",
  "03 机器人 飞船维护工": "robot_return_ship_1",
  "01 机器人 居住舱维修工": "robot_habitat_1",
  "02 机器人 温室维修工": "robot_greenhouse_1",
  "03 机器人 制氧站维修工": "robot_oxygen_1",
  "04 机器人 燃料厂维修工": "robot_methane_1",
  "05 机器人 车库维修工": "robot_garage_1",
  "06 机器人 通信塔维修工": "robot_tower_1",
  "07 机器人 科研舱维修工": "robot_lab_1",
  "08 机器人 物资仓维修工": "robot_storehouse_1",
  "09 机器人 医疗舱维修工": "robot_medical_1",
  "10 机器人 阵列 A 维修工": "robot_solar_a_1",
  "11 机器人 阵列 B 维修工": "robot_solar_b_1",
  "12 机器人 阵列 C 维修工": "robot_solar_c_1",
};
